name: Terraform Apply

on:
  push:
    branches:
      - main   # run on pushes to main branch

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    env:
      TERRAFORM_VERSION: "0.15.3"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1    # adjust region if needed

      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/${{ env.TERRAFORM_VERSION }}/terraform_${{ env.TERRAFORM_VERSION }}_linux_amd64.zip
          unzip terraform_${{ env.TERRAFORM_VERSION }}_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform --version

      - name: Terraform Apply
        run: |
          echo "Starting terraform apply at $(date)"
          cd part1
          terraform init -input=false --backend-config=dev.conf
          terraform apply -auto-approve -var-file=dev.tfvars
