name: Terraform CI

on:
  push:
    branches:
      - main   

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TERRAFORM_VERSION: "1.5.7"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform --version

      - name: Terraform Init and Plan
      - working-directory: part1
        run: |
         terraform init 
         terraform validate
         terraform  plan 